/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package feel_gemini.screen;

import feel_gemini.MainFrame;

/**
 *
 * @author ad
 */
public class SettingPanel extends javax.swing.JPanel {

    private MainFrame mainFrame; 
    
    public SettingPanel() {
        initComponents();
    }
    
    public SettingPanel(MainFrame aThis) {
        this.mainFrame = aThis;   // nếu bạn có biến mainFrame, dùng để gọi lại MainFrame
        initComponents();         // luôn cần để giao diện hiển thị
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Setting = new javax.swing.JLabel();
        jButton_Backscreen_S = new javax.swing.JButton();
        jButton_Closescreen_S = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel_Size = new javax.swing.JLabel();
        jTextField_Size = new javax.swing.JTextField();
        jLabel_TypeReading = new javax.swing.JLabel();
        jCheckBox_typevn = new javax.swing.JCheckBox();
        jCheckBox_english = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));

        jLabel_Setting.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_Setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Setting.setText("SETTING");
        jLabel_Setting.setMaximumSize(new java.awt.Dimension(150, 32));
        jLabel_Setting.setMinimumSize(new java.awt.Dimension(150, 32));
        jLabel_Setting.setPreferredSize(new java.awt.Dimension(150, 32));

        jButton_Backscreen_S.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton_Backscreen_S.setText("BACK");
        jButton_Backscreen_S.setMaximumSize(new java.awt.Dimension(75, 25));
        jButton_Backscreen_S.setMinimumSize(new java.awt.Dimension(75, 25));
        jButton_Backscreen_S.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton_Backscreen_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Backscreen_SActionPerformed(evt);
            }
        });

        jButton_Closescreen_S.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton_Closescreen_S.setText("CLOSE");
        jButton_Closescreen_S.setMaximumSize(new java.awt.Dimension(75, 25));
        jButton_Closescreen_S.setMinimumSize(new java.awt.Dimension(75, 25));
        jButton_Closescreen_S.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton_Closescreen_S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Closescreen_SActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 51, 51));
        jSeparator1.setMaximumSize(new java.awt.Dimension(388, 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(388, 5));
        jSeparator1.setPreferredSize(new java.awt.Dimension(388, 5));

        jLabel_Size.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Size.setText("SIZE");

        jTextField_Size.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabel_TypeReading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TypeReading.setText("TYPE");

        jCheckBox_typevn.setText("Vietnamese");

        jCheckBox_english.setText("English");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Backscreen_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel_Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Closescreen_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_Size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_TypeReading, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_english)
                            .addComponent(jCheckBox_typevn))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Closescreen_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Backscreen_S, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Size, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_Size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_TypeReading, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_typevn))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox_english)
                .addContainerGap(357, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_Backscreen_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Backscreen_SActionPerformed
        // TODO add your handling code here:
        // Chuyển về Home. Screen1 vẫn là component trong mainPanel, trạng thái được giữ.
        mainFrame.showScreen("Home");
    }//GEN-LAST:event_jButton_Backscreen_SActionPerformed

    private void jButton_Closescreen_SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Closescreen_SActionPerformed
        // TODO add your handling code here:
        // Gọi MainFrame để loại bỏ component và gán null.
        mainFrame.closeScreen("Setting");
    }//GEN-LAST:event_jButton_Closescreen_SActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Backscreen_S;
    private javax.swing.JButton jButton_Closescreen_S;
    private javax.swing.JCheckBox jCheckBox_english;
    private javax.swing.JCheckBox jCheckBox_typevn;
    private javax.swing.JLabel jLabel_Setting;
    private javax.swing.JLabel jLabel_Size;
    private javax.swing.JLabel jLabel_TypeReading;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_Size;
    // End of variables declaration//GEN-END:variables
}
